version: '3.7'
services:
  catgpt:
    container_name: catgpt
    image: "cr.yandex/crpfselct7kq21c59cab/catgpt:1.0"
    restart: always
    network_mode: "host"
  unifiedagent:
    container_name: unified-agent
    image: "cr.yandex/yc/unified-agent"
    environment:
      FOLDER_ID: "${folder_id}"
    restart: always
    network_mode: "host"
    volumes:
      - /ua:/etc/yandex/unified_agent/conf.d