name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build
        run: |
          cd catgpt
          go build -o app
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: cr.yandex/crpfselct7kq21c59cab
          CR_REPOSITORY: catgpt
          IMAGE_TAG: ${{ github.sha }}
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo $(pwd)
          echo $(ls)
          cd catgpt
          yc container registry configure-docker
          docker build -t $CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push $CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG